import type { Metadata } from "next";
import { Poppins, Inter } from 'next/font/google'
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = {
  subset: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-poppins'
}

const inter = {
  subset: ['latin'],
  weight: ['400', '500'],
  variable: '--font-inter'
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
